# Generated by Django 5.0.6 on 2024-07-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0003_alter_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
